= Cloud Native Architecture Patterns with Spring Cloud and Cloud Foundry

Devoxx Poland Hands-on Lab Student Guide

== Instructor Details

Matt Stine (https://twitter.com/mstine[@mstine]) +
Cloud Native Architect +
Strategic Product Organization +
Pivotal +
mstine@pivotal.io

== Prerequsities

include::prerequisites.adoc[]

== First Things First

Add your name and the email address you used to sign up for Pivotal Web Services to an empty row in https://docs.google.com/spreadsheets/d/1YbJLcjEmdsZd3jKZ8eiMUAJCPKZsFNyTEKzlmLWKfVw/edit#gid=0[this Google spreadsheet]. I will invite you to a organization and space to use for this class.

== Course Materials

* link:lab_01.html[Lab 1 - Getting Started with Spring Boot]
* link:lab_02.html[Lab 2 - Introspection, Monitoring, and Metrics using Spring Boot Actuator]
* link:lab_03.html[Lab 3 - Composing Cloud Native Architectures with Spring Cloud]
* link:lab_04.html[Lab 4 - Operating Cloud Native Architectures with Spring Cloud]
* link:lab_05.html[Lab 5 - Deploying Cloud Native Architectures to Cloud Foundry]
